#!/usr/bin/env bash

set -e

if [[ -z "$CLJS_SCRIPT_QUIET" ]]; then
  set -x
fi

CLOJURESCRIPT_HOME=$(cd $(dirname $0)/.. && pwd)

CLJS_SCRIPT_MVN_OPTS=${CLJS_SCRIPT_MVN_OPTS:-""}

CP_FILE=$(mktemp /tmp/cljs_cp.txt.XXXXXXXXXXX)

mvn -f pom.template.xml dependency:build-classpath -Dmdep.outputFile=$CP_FILE $CLJS_SCRIPT_MVN_OPTS

CLJS_CP=$(cat $CP_FILE)$(${CLOJURESCRIPT_HOME}/bin/classpath_conv ":src/main/clojure:src/main/cljs")

# For Hudson server
if [ "$HUDSON" = "true" ]; then
    JAVA_CMD=$JAVA_HOME/bin/java
else
    JAVA_CMD="java"
fi
$JAVA_CMD -server -cp $CLJS_CP clojure.main ${CLOJURESCRIPT_HOME}/script/aot.clj
