#!/usr/bin/env bash

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJSC_CP=''
for next in lib/*: src/main/clojure: src/main/cljs: test/cljs; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done

java -server -cp $($CLOJURESCRIPT_HOME/bin/classpath_conv $CLJSC_CP) clojure.main -e "
(require '[cljs.repl :as r])
(require '[cljs.repl.browser :as b])
(r/repl (b/repl-env))
"
