#!/usr/bin/env bash

if [ ! -f target/cljs.jar ]; then
  echo "Run script/uberjar first"
  exit 1
fi

CLOJURESCRIPT_HOME=$(cd $(dirname $0)/.. && pwd)

java -Dfile.encoding=UTF-8 \
     -cp $(${CLOJURESCRIPT_HOME}/bin/classpath_conv target/cljs.jar:src/test/cljs_cli) \
     clojure.main -m cljs-cli.test-runner "$@"
