#!/usr/bin/env bash

rm -rf builds/out-adv
rm -rf out
rm -rf target
rm -rf package.json
rm -rf package-lock.json

echo {} > package.json
mkdir -p builds/out-adv

COMPILE_OUTPUT=builds/out-adv/core-advanced-test.js

if ! bin/cljsc src/test/cljs "{:optimizations :advanced
                               :main test-runner
                               :output-wrapper true
                               :verbose true
                               :compiler-stats true
                               :parallel-build true
                               :output-dir \"builds/out-adv\"
                               :npm-deps {:lodash \"4.17.4\"}
                               :closure-warnings {:non-standard-jsdoc :off :global-this :off}
                               :install-deps true
                               :language-in :es6
                               :language-out :es5
                               :foreign-libs [{:file \"src/test/cljs/calculator_global.js\"
                                               :provides [\"calculator\"]
                                               :global-exports {calculator Calculator}}
                                              {:file \"src/test/cljs/es6_dep.js\"
                                               :module-type :es6
                                               :provides [\"es6_calc\"]}
                                              {:file \"src/test/cljs/calculator.js\"
                                               :module-type :commonjs
                                               :provides [\"calculator\"]}
                                              {:file \"src/test/cljs/es6_default_hello.js\"
                                               :provides [\"es6_default_hello\"]
                                               :module-type :es6}]}" > $COMPILE_OUTPUT; then
  >&2 echo ClojureScript compilation failed
  exit 1
fi;

exec ./script/test-runner $COMPILE_OUTPUT
