#!/usr/bin/env bash

echo "Generating sample javascript"
mkdir compilation

cat >compilation/test.js <<EOF
function create_alert(msg) {
    alert(msg);
}
EOF

echo "Testing compilation"
cd compilation
for file in *
do
  if [ -f "$file" ] ; then
    name=${file%.*}
    java -jar $(ls ../lib/closure-compiler-v*.jar) --js "$file" --js_output_file "$name-compiled.js"
  fi
done
cd ..

echo -e "\nOriginal:"
cat compilation/test.js

echo -e "\nOptimized:"
cat compilation/test-compiled.js

echo -e "\nCleaning up"
rm -rf compilation
